"""this file contains all the constants used in the game"""

import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

BLACK = (0, 0, 0)

MAP_SIZE = 300

BUTTON_RECT = os.path.join(ROOT_DIR, 'assets', 'Options Rect.png')
BUTTON_FONT = os.path.join(ROOT_DIR, 'assets', 'font.ttf')
BUTTON_BASE_COLOR = '#d7fcd4'

SOLDIER_HITBOX = 3
SOLDIER_SPEED = 2
SOLDIER_ANIMATION_COOLDOWN = 100

SOLDIER_NPC_MOVE_FREQUENCY = 500
SOLDIER_NPC_SPEED = 1
SOLDIER_NPC_FIRE_DELAY = 400
SOLDIER_BURST_LENGTH = 10

PLAYER_DEFAULT_SOLDIER_PATH = os.path.join(ROOT_DIR, 'assets', 'soldier_with_gun.png')
PLAYER_DEAD_SOLDIER_PATH = os.path.join(ROOT_DIR, 'assets', 'dead_body_black.png')

NPC_RED_SOLDIER_PATH = os.path.join(ROOT_DIR, 'assets', 'soldier_with_gun_red.png')
NPC_RED_DEAD_SOLDIER_PATH = os.path.join(ROOT_DIR, 'assets', 'dead_body_red.png')

SOLDIER_ANIMATION_STEPS = 6
SOLDIER_PIC_WIDTH = 76
SOLDIER_PIC_HEIGHT = 70
SOLDIER_PIC_SCALE = 0.6

DEAD_SOLDIER_PIC_WIDTH = 159
DEAD_SOLDIER_PIC_HEIGHT = 89
DEAD_SOLDIER_PIC_SCALE = 0.5

BULLET_HITBOX = 1
BULLET_ANIMATION_COOLDOWN = 0.1
BULLET_SPEED = 6
BULLET_LOCATION = os.path.join(ROOT_DIR, 'assets', 'SpongeBullet.png')

ENVIRONMENT_BROWN_BRICK_PATH = os.path.join(ROOT_DIR, 'assets', 'brown_bricks.png')
ENVIRONMENT_BROWN_BRICK_SCALE = 1
ENVIRONMENT_BROWN_BRICK_WIDTH = 32
ENVIRONMENT_BROWN_BRICK_HEIGHT = 32

ENVIRONMENT_KITCHEN_FLOOR_PATH = os.path.join(ROOT_DIR, 'assets', 'kitchen_floor.png')
ENVIRONMENT_KITCHEN_FLOOR_SCALE = 1
ENVIRONMENT_KITCHEN_FLOOR_WIDTH = 16
ENVIRONMENT_KITCHEN_FLOOR_HEIGHT = 16

ENVIRONMENT_CARPET_PATH = os.path.join(ROOT_DIR, 'assets', 'carpet.png')
ENVIRONMENT_CARPET_SCALE = 1
ENVIRONMENT_CARPET_WIDTH = 5
ENVIRONMENT_CARPET_HEIGHT = 5

ENVIRONMENT_THIN_WALL_PATH = os.path.join(ROOT_DIR, 'assets', 'thin_wall.png')
ENVIRONMENT_THIN_WALL_SCALE = 4
ENVIRONMENT_THIN_WALL_WIDTH = 8
ENVIRONMENT_THIN_WALL_HEIGHT = 8
ENVIRONMENT_THIN_WALL_HITBOX = 5

ENVIRONMENT_THICK_WALL_PATH = os.path.join(ROOT_DIR, 'assets', 'thick_wall.png')
ENVIRONMENT_THICK_WALL_SCALE = 2
ENVIRONMENT_THICK_WALL_WIDTH = 21
ENVIRONMENT_THICK_WALL_HEIGHT = 21
ENVIRONMENT_THICK_WALL_HITBOX = 6

ENVIRONMENT_KITCHEN_SINK_PATH = os.path.join(ROOT_DIR, 'assets', 'kitchen_sink.png')
ENVIRONMENT_KITCHEN_SINK_SCALE = 2
ENVIRONMENT_KITCHEN_SINK_WIDTH = 29
ENVIRONMENT_KITCHEN_SINK_HEIGHT = 23
ENVIRONMENT_KITCHEN_SINK_HITBOX = 10

ENVIRONMENT_KITCHEN_OVEN_PATH = os.path.join(ROOT_DIR, 'assets', 'kitchen_oven.png')
ENVIRONMENT_KITCHEN_OVEN_SCALE = 2
ENVIRONMENT_KITCHEN_OVEN_WIDTH = 24
ENVIRONMENT_KITCHEN_OVEN_HEIGHT = 22
ENVIRONMENT_KITCHEN_OVEN_HITBOX = 10

ENVIRONMENT_PIANO_PATH = os.path.join(ROOT_DIR, 'assets', 'piano.png')
ENVIRONMENT_PIANO_SCALE = 2
ENVIRONMENT_PIANO_WIDTH = 28
ENVIRONMENT_PIANO_HEIGHT = 28
ENVIRONMENT_PIANO_HITBOX = 10

ENVIRONMENT_ROTTEN_TABLE_PATH = os.path.join(ROOT_DIR, 'assets', 'rotten_table.png')
ENVIRONMENT_ROTTEN_TABLE_SCALE = 2
ENVIRONMENT_ROTTEN_TABLE_WIDTH = 30
ENVIRONMENT_ROTTEN_TABLE_HEIGHT = 30
ENVIRONMENT_ROTTEN_TABLE_HITBOX = 10

ENVIRONMENT_NEXT_TO_ROTTEN_PATH = os.path.join(ROOT_DIR, 'assets', 'next_to_rotten.png')
ENVIRONMENT_NEXT_TO_ROTTEN_SCALE = 2
ENVIRONMENT_NEXT_TO_ROTTEN_WIDTH = 30
ENVIRONMENT_NEXT_TO_ROTTEN_HEIGHT = 30
ENVIRONMENT_NEXT_TO_ROTTEN_HITBOX = 10

ENVIRONMENT_CAR_PATH = os.path.join(ROOT_DIR, 'assets', 'car.png')
ENVIRONMENT_CAR_SCALE = 1.5
ENVIRONMENT_CAR_WIDTH = 176
ENVIRONMENT_CAR_HEIGHT = 74
ENVIRONMENT_CAR_HITBOX = 1
