"""Handles loading images and creating backgrounds."""
import pygame


# author: russs123
# https://github.com/russs123/pygame_tutorials/blob/main/sprite_tutorial/spritesheet.py
# pylint: disable=R0913
# arguments are fine here
def get_image(sheet, frame, cwidth, cheight, scale, colour):
    """This function returns image from sprite sheet.
    It can return only one frame from animation."""
    image = pygame.Surface((cwidth, cheight)).convert_alpha()
    image.blit(sheet, (0, 0), area=((cwidth * frame), 0, cwidth, cheight))
    image = pygame.transform.scale(image, (cwidth * scale, cheight * scale)).convert_alpha()
    image.set_colorkey(colour)
    return image


# generated by chatgpt
def make_background(image, screen_info):
    """This function creates background from image."""
    screen_size = (screen_info.current_w, screen_info.current_h)

    background = pygame.Surface(screen_size)
    small_image_width, small_image_height = image.get_size()

    for x in range(0, screen_size[0], small_image_width):
        for y in range(0, screen_size[1], small_image_height):
            background.blit(image, (x, y))

    return background
